/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NetworkRouteRouteImport } from './routes/$network/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as NetworkIndexRouteImport } from './routes/$network/index'
import { Route as NetworkSearchRouteImport } from './routes/$network/search'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard/approvals'
import { Route as DashboardRailsRouteImport } from './routes/dashboard/rails'
import { Route as DashboardSessionKeysRouteImport } from './routes/dashboard/session-keys'
import { Route as DashboardSetupRouteImport } from './routes/dashboard/setup'
import { Route as DashboardUploadRouteImport } from './routes/dashboard/upload'
import { Route as NetworkAddressAddressRouteImport } from './routes/$network/address/$address'
import { Route as NetworkDataSetsIndexRouteImport } from './routes/$network/data-sets/index'
import { Route as NetworkDataSetsIdRouteImport } from './routes/$network/data-sets/$id'
import { Route as NetworkPiecesCidRouteImport } from './routes/$network/pieces/$cid'
import { Route as NetworkProvidersIndexRouteImport } from './routes/$network/providers/index'
import { Route as NetworkProvidersIdRouteImport } from './routes/$network/providers/$id'
import { Route as NetworkRailsIndexRouteImport } from './routes/$network/rails/index'
import { Route as NetworkRailsIdRouteImport } from './routes/$network/rails/$id'
import { Route as NetworkSessionKeysIndexRouteImport } from './routes/$network/session-keys/index'
import { Route as DashboardDataSetsIndexRouteImport } from './routes/dashboard/data-sets/index'
import { Route as DashboardDataSetsIdRouteImport } from './routes/dashboard/data-sets/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRouteRoute = NetworkRouteRouteImport.update({
  id: '/$network',
  path: '/$network',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkIndexRoute = NetworkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkSearchRoute = NetworkSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRailsRoute = DashboardRailsRouteImport.update({
  id: '/rails',
  path: '/rails',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSessionKeysRoute = DashboardSessionKeysRouteImport.update({
  id: '/session-keys',
  path: '/session-keys',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSetupRoute = DashboardSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const NetworkAddressAddressRoute = NetworkAddressAddressRouteImport.update({
  id: '/address/$address',
  path: '/address/$address',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkDataSetsIndexRoute = NetworkDataSetsIndexRouteImport.update({
  id: '/data-sets/',
  path: '/data-sets/',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkDataSetsIdRoute = NetworkDataSetsIdRouteImport.update({
  id: '/data-sets/$id',
  path: '/data-sets/$id',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkPiecesCidRoute = NetworkPiecesCidRouteImport.update({
  id: '/pieces/$cid',
  path: '/pieces/$cid',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkProvidersIndexRoute = NetworkProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkProvidersIdRoute = NetworkProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkRailsIndexRoute = NetworkRailsIndexRouteImport.update({
  id: '/rails/',
  path: '/rails/',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkRailsIdRoute = NetworkRailsIdRouteImport.update({
  id: '/rails/$id',
  path: '/rails/$id',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkSessionKeysIndexRoute = NetworkSessionKeysIndexRouteImport.update({
  id: '/session-keys/',
  path: '/session-keys/',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const DashboardDataSetsIndexRoute = DashboardDataSetsIndexRouteImport.update({
  id: '/data-sets/',
  path: '/data-sets/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDataSetsIdRoute = DashboardDataSetsIdRouteImport.update({
  id: '/data-sets/$id',
  path: '/data-sets/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$network': typeof NetworkRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$network/search': typeof NetworkSearchRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/rails': typeof DashboardRailsRoute
  '/dashboard/session-keys': typeof DashboardSessionKeysRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/$network/': typeof NetworkIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$network/address/$address': typeof NetworkAddressAddressRoute
  '/$network/data-sets/$id': typeof NetworkDataSetsIdRoute
  '/$network/pieces/$cid': typeof NetworkPiecesCidRoute
  '/$network/providers/$id': typeof NetworkProvidersIdRoute
  '/$network/rails/$id': typeof NetworkRailsIdRoute
  '/dashboard/data-sets/$id': typeof DashboardDataSetsIdRoute
  '/$network/data-sets/': typeof NetworkDataSetsIndexRoute
  '/$network/providers/': typeof NetworkProvidersIndexRoute
  '/$network/rails/': typeof NetworkRailsIndexRoute
  '/$network/session-keys/': typeof NetworkSessionKeysIndexRoute
  '/dashboard/data-sets/': typeof DashboardDataSetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$network/search': typeof NetworkSearchRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/rails': typeof DashboardRailsRoute
  '/dashboard/session-keys': typeof DashboardSessionKeysRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/$network': typeof NetworkIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/$network/address/$address': typeof NetworkAddressAddressRoute
  '/$network/data-sets/$id': typeof NetworkDataSetsIdRoute
  '/$network/pieces/$cid': typeof NetworkPiecesCidRoute
  '/$network/providers/$id': typeof NetworkProvidersIdRoute
  '/$network/rails/$id': typeof NetworkRailsIdRoute
  '/dashboard/data-sets/$id': typeof DashboardDataSetsIdRoute
  '/$network/data-sets': typeof NetworkDataSetsIndexRoute
  '/$network/providers': typeof NetworkProvidersIndexRoute
  '/$network/rails': typeof NetworkRailsIndexRoute
  '/$network/session-keys': typeof NetworkSessionKeysIndexRoute
  '/dashboard/data-sets': typeof DashboardDataSetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$network': typeof NetworkRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$network/search': typeof NetworkSearchRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/rails': typeof DashboardRailsRoute
  '/dashboard/session-keys': typeof DashboardSessionKeysRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/$network/': typeof NetworkIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$network/address/$address': typeof NetworkAddressAddressRoute
  '/$network/data-sets/$id': typeof NetworkDataSetsIdRoute
  '/$network/pieces/$cid': typeof NetworkPiecesCidRoute
  '/$network/providers/$id': typeof NetworkProvidersIdRoute
  '/$network/rails/$id': typeof NetworkRailsIdRoute
  '/dashboard/data-sets/$id': typeof DashboardDataSetsIdRoute
  '/$network/data-sets/': typeof NetworkDataSetsIndexRoute
  '/$network/providers/': typeof NetworkProvidersIndexRoute
  '/$network/rails/': typeof NetworkRailsIndexRoute
  '/$network/session-keys/': typeof NetworkSessionKeysIndexRoute
  '/dashboard/data-sets/': typeof DashboardDataSetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$network'
    | '/dashboard'
    | '/$network/search'
    | '/dashboard/account'
    | '/dashboard/approvals'
    | '/dashboard/rails'
    | '/dashboard/session-keys'
    | '/dashboard/setup'
    | '/dashboard/upload'
    | '/$network/'
    | '/dashboard/'
    | '/$network/address/$address'
    | '/$network/data-sets/$id'
    | '/$network/pieces/$cid'
    | '/$network/providers/$id'
    | '/$network/rails/$id'
    | '/dashboard/data-sets/$id'
    | '/$network/data-sets/'
    | '/$network/providers/'
    | '/$network/rails/'
    | '/$network/session-keys/'
    | '/dashboard/data-sets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$network/search'
    | '/dashboard/account'
    | '/dashboard/approvals'
    | '/dashboard/rails'
    | '/dashboard/session-keys'
    | '/dashboard/setup'
    | '/dashboard/upload'
    | '/$network'
    | '/dashboard'
    | '/$network/address/$address'
    | '/$network/data-sets/$id'
    | '/$network/pieces/$cid'
    | '/$network/providers/$id'
    | '/$network/rails/$id'
    | '/dashboard/data-sets/$id'
    | '/$network/data-sets'
    | '/$network/providers'
    | '/$network/rails'
    | '/$network/session-keys'
    | '/dashboard/data-sets'
  id:
    | '__root__'
    | '/'
    | '/$network'
    | '/dashboard'
    | '/$network/search'
    | '/dashboard/account'
    | '/dashboard/approvals'
    | '/dashboard/rails'
    | '/dashboard/session-keys'
    | '/dashboard/setup'
    | '/dashboard/upload'
    | '/$network/'
    | '/dashboard/'
    | '/$network/address/$address'
    | '/$network/data-sets/$id'
    | '/$network/pieces/$cid'
    | '/$network/providers/$id'
    | '/$network/rails/$id'
    | '/dashboard/data-sets/$id'
    | '/$network/data-sets/'
    | '/$network/providers/'
    | '/$network/rails/'
    | '/$network/session-keys/'
    | '/dashboard/data-sets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetworkRouteRoute: typeof NetworkRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$network': {
      id: '/$network'
      path: '/$network'
      fullPath: '/$network'
      preLoaderRoute: typeof NetworkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$network/': {
      id: '/$network/'
      path: '/'
      fullPath: '/$network/'
      preLoaderRoute: typeof NetworkIndexRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/search': {
      id: '/$network/search'
      path: '/search'
      fullPath: '/$network/search'
      preLoaderRoute: typeof NetworkSearchRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rails': {
      id: '/dashboard/rails'
      path: '/rails'
      fullPath: '/dashboard/rails'
      preLoaderRoute: typeof DashboardRailsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/session-keys': {
      id: '/dashboard/session-keys'
      path: '/session-keys'
      fullPath: '/dashboard/session-keys'
      preLoaderRoute: typeof DashboardSessionKeysRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setup': {
      id: '/dashboard/setup'
      path: '/setup'
      fullPath: '/dashboard/setup'
      preLoaderRoute: typeof DashboardSetupRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/$network/address/$address': {
      id: '/$network/address/$address'
      path: '/address/$address'
      fullPath: '/$network/address/$address'
      preLoaderRoute: typeof NetworkAddressAddressRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/data-sets/': {
      id: '/$network/data-sets/'
      path: '/data-sets'
      fullPath: '/$network/data-sets/'
      preLoaderRoute: typeof NetworkDataSetsIndexRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/data-sets/$id': {
      id: '/$network/data-sets/$id'
      path: '/data-sets/$id'
      fullPath: '/$network/data-sets/$id'
      preLoaderRoute: typeof NetworkDataSetsIdRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/pieces/$cid': {
      id: '/$network/pieces/$cid'
      path: '/pieces/$cid'
      fullPath: '/$network/pieces/$cid'
      preLoaderRoute: typeof NetworkPiecesCidRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/providers/': {
      id: '/$network/providers/'
      path: '/providers'
      fullPath: '/$network/providers/'
      preLoaderRoute: typeof NetworkProvidersIndexRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/providers/$id': {
      id: '/$network/providers/$id'
      path: '/providers/$id'
      fullPath: '/$network/providers/$id'
      preLoaderRoute: typeof NetworkProvidersIdRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/rails/': {
      id: '/$network/rails/'
      path: '/rails'
      fullPath: '/$network/rails/'
      preLoaderRoute: typeof NetworkRailsIndexRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/rails/$id': {
      id: '/$network/rails/$id'
      path: '/rails/$id'
      fullPath: '/$network/rails/$id'
      preLoaderRoute: typeof NetworkRailsIdRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/session-keys/': {
      id: '/$network/session-keys/'
      path: '/session-keys'
      fullPath: '/$network/session-keys/'
      preLoaderRoute: typeof NetworkSessionKeysIndexRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/dashboard/data-sets/': {
      id: '/dashboard/data-sets/'
      path: '/data-sets'
      fullPath: '/dashboard/data-sets/'
      preLoaderRoute: typeof DashboardDataSetsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/data-sets/$id': {
      id: '/dashboard/data-sets/$id'
      path: '/data-sets/$id'
      fullPath: '/dashboard/data-sets/$id'
      preLoaderRoute: typeof DashboardDataSetsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface NetworkRouteRouteChildren {
  NetworkSearchRoute: typeof NetworkSearchRoute
  NetworkIndexRoute: typeof NetworkIndexRoute
  NetworkAddressAddressRoute: typeof NetworkAddressAddressRoute
  NetworkDataSetsIdRoute: typeof NetworkDataSetsIdRoute
  NetworkPiecesCidRoute: typeof NetworkPiecesCidRoute
  NetworkProvidersIdRoute: typeof NetworkProvidersIdRoute
  NetworkRailsIdRoute: typeof NetworkRailsIdRoute
  NetworkDataSetsIndexRoute: typeof NetworkDataSetsIndexRoute
  NetworkProvidersIndexRoute: typeof NetworkProvidersIndexRoute
  NetworkRailsIndexRoute: typeof NetworkRailsIndexRoute
  NetworkSessionKeysIndexRoute: typeof NetworkSessionKeysIndexRoute
}

const NetworkRouteRouteChildren: NetworkRouteRouteChildren = {
  NetworkSearchRoute: NetworkSearchRoute,
  NetworkIndexRoute: NetworkIndexRoute,
  NetworkAddressAddressRoute: NetworkAddressAddressRoute,
  NetworkDataSetsIdRoute: NetworkDataSetsIdRoute,
  NetworkPiecesCidRoute: NetworkPiecesCidRoute,
  NetworkProvidersIdRoute: NetworkProvidersIdRoute,
  NetworkRailsIdRoute: NetworkRailsIdRoute,
  NetworkDataSetsIndexRoute: NetworkDataSetsIndexRoute,
  NetworkProvidersIndexRoute: NetworkProvidersIndexRoute,
  NetworkRailsIndexRoute: NetworkRailsIndexRoute,
  NetworkSessionKeysIndexRoute: NetworkSessionKeysIndexRoute,
}

const NetworkRouteRouteWithChildren = NetworkRouteRoute._addFileChildren(
  NetworkRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardRailsRoute: typeof DashboardRailsRoute
  DashboardSessionKeysRoute: typeof DashboardSessionKeysRoute
  DashboardSetupRoute: typeof DashboardSetupRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDataSetsIdRoute: typeof DashboardDataSetsIdRoute
  DashboardDataSetsIndexRoute: typeof DashboardDataSetsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardRailsRoute: DashboardRailsRoute,
  DashboardSessionKeysRoute: DashboardSessionKeysRoute,
  DashboardSetupRoute: DashboardSetupRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDataSetsIdRoute: DashboardDataSetsIdRoute,
  DashboardDataSetsIndexRoute: DashboardDataSetsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetworkRouteRoute: NetworkRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
