/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NetworkRouteRouteImport } from './routes/$network/route'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NetworkIndexRouteImport } from './routes/$network/index'
import { Route as NetworkSearchRouteImport } from './routes/$network/search'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known/api-catalog'
import { Route as DotwellKnownMcpServerCardRouteImport } from './routes/[.]well-known/mcp-server-card'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard/approvals'
import { Route as DashboardRailsRouteImport } from './routes/dashboard/rails'
import { Route as DashboardSessionKeysRouteImport } from './routes/dashboard/session-keys'
import { Route as DashboardSetupRouteImport } from './routes/dashboard/setup'
import { Route as DashboardUploadRouteImport } from './routes/dashboard/upload'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as NetworkAddressAddressRouteImport } from './routes/$network/address/$address'
import { Route as NetworkDataSetsIndexRouteImport } from './routes/$network/data-sets/index'
import { Route as NetworkDataSetsIdRouteImport } from './routes/$network/data-sets/$id'
import { Route as NetworkPiecesCidRouteImport } from './routes/$network/pieces/$cid'
import { Route as NetworkProvidersIndexRouteImport } from './routes/$network/providers/index'
import { Route as NetworkProvidersIdRouteImport } from './routes/$network/providers/$id'
import { Route as NetworkRailsIndexRouteImport } from './routes/$network/rails/index'
import { Route as NetworkRailsIdRouteImport } from './routes/$network/rails/$id'
import { Route as NetworkSessionKeysIndexRouteImport } from './routes/$network/session-keys/index'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.]well-known/agent-skills/index[.]json'
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from './routes/[.]well-known/mcp/server-card[.]json'
import { Route as DashboardDataSetsIndexRouteImport } from './routes/dashboard/data-sets/index'
import { Route as DashboardDataSetsIdRouteImport } from './routes/dashboard/data-sets/$id'
import { Route as DotwellKnownAgentSkillsFilSKILLDotmdRouteImport } from './routes/[.]well-known/agent-skills/fil/SKILL[.]md'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRouteRoute = NetworkRouteRouteImport.update({
  id: '/$network',
  path: '/$network',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkIndexRoute = NetworkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkSearchRoute = NetworkSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMcpServerCardRoute =
  DotwellKnownMcpServerCardRouteImport.update({
    id: '/.well-known/mcp-server-card',
    path: '/.well-known/mcp-server-card',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRailsRoute = DashboardRailsRouteImport.update({
  id: '/rails',
  path: '/rails',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSessionKeysRoute = DashboardSessionKeysRouteImport.update({
  id: '/session-keys',
  path: '/session-keys',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSetupRoute = DashboardSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRouteRoute,
} as any)
const NetworkAddressAddressRoute = NetworkAddressAddressRouteImport.update({
  id: '/address/$address',
  path: '/address/$address',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkDataSetsIndexRoute = NetworkDataSetsIndexRouteImport.update({
  id: '/data-sets/',
  path: '/data-sets/',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkDataSetsIdRoute = NetworkDataSetsIdRouteImport.update({
  id: '/data-sets/$id',
  path: '/data-sets/$id',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkPiecesCidRoute = NetworkPiecesCidRouteImport.update({
  id: '/pieces/$cid',
  path: '/pieces/$cid',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkProvidersIndexRoute = NetworkProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkProvidersIdRoute = NetworkProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkRailsIndexRoute = NetworkRailsIndexRouteImport.update({
  id: '/rails/',
  path: '/rails/',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkRailsIdRoute = NetworkRailsIdRouteImport.update({
  id: '/rails/$id',
  path: '/rails/$id',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkSessionKeysIndexRoute = NetworkSessionKeysIndexRouteImport.update({
  id: '/session-keys/',
  path: '/session-keys/',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/.well-known/mcp/server-card.json',
    path: '/.well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardDataSetsIndexRoute = DashboardDataSetsIndexRouteImport.update({
  id: '/data-sets/',
  path: '/data-sets/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDataSetsIdRoute = DashboardDataSetsIdRouteImport.update({
  id: '/data-sets/$id',
  path: '/data-sets/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DotwellKnownAgentSkillsFilSKILLDotmdRoute =
  DotwellKnownAgentSkillsFilSKILLDotmdRouteImport.update({
    id: '/.well-known/agent-skills/fil/SKILL.md',
    path: '/.well-known/agent-skills/fil/SKILL.md',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$network': typeof NetworkRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/agents': typeof AgentsRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$network/search': typeof NetworkSearchRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/mcp-server-card': typeof DotwellKnownMcpServerCardRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/rails': typeof DashboardRailsRoute
  '/dashboard/session-keys': typeof DashboardSessionKeysRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/$network/': typeof NetworkIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/$network/address/$address': typeof NetworkAddressAddressRoute
  '/$network/data-sets/$id': typeof NetworkDataSetsIdRoute
  '/$network/pieces/$cid': typeof NetworkPiecesCidRoute
  '/$network/providers/$id': typeof NetworkProvidersIdRoute
  '/$network/rails/$id': typeof NetworkRailsIdRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/dashboard/data-sets/$id': typeof DashboardDataSetsIdRoute
  '/$network/data-sets/': typeof NetworkDataSetsIndexRoute
  '/$network/providers/': typeof NetworkProvidersIndexRoute
  '/$network/rails/': typeof NetworkRailsIndexRoute
  '/$network/session-keys/': typeof NetworkSessionKeysIndexRoute
  '/dashboard/data-sets/': typeof DashboardDataSetsIndexRoute
  '/.well-known/agent-skills/fil/SKILL.md': typeof DotwellKnownAgentSkillsFilSKILLDotmdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$network/search': typeof NetworkSearchRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/mcp-server-card': typeof DotwellKnownMcpServerCardRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/rails': typeof DashboardRailsRoute
  '/dashboard/session-keys': typeof DashboardSessionKeysRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/$network': typeof NetworkIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/$network/address/$address': typeof NetworkAddressAddressRoute
  '/$network/data-sets/$id': typeof NetworkDataSetsIdRoute
  '/$network/pieces/$cid': typeof NetworkPiecesCidRoute
  '/$network/providers/$id': typeof NetworkProvidersIdRoute
  '/$network/rails/$id': typeof NetworkRailsIdRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/dashboard/data-sets/$id': typeof DashboardDataSetsIdRoute
  '/$network/data-sets': typeof NetworkDataSetsIndexRoute
  '/$network/providers': typeof NetworkProvidersIndexRoute
  '/$network/rails': typeof NetworkRailsIndexRoute
  '/$network/session-keys': typeof NetworkSessionKeysIndexRoute
  '/dashboard/data-sets': typeof DashboardDataSetsIndexRoute
  '/.well-known/agent-skills/fil/SKILL.md': typeof DotwellKnownAgentSkillsFilSKILLDotmdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$network': typeof NetworkRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/agents': typeof AgentsRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$network/search': typeof NetworkSearchRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/mcp-server-card': typeof DotwellKnownMcpServerCardRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/rails': typeof DashboardRailsRoute
  '/dashboard/session-keys': typeof DashboardSessionKeysRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/$network/': typeof NetworkIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/$network/address/$address': typeof NetworkAddressAddressRoute
  '/$network/data-sets/$id': typeof NetworkDataSetsIdRoute
  '/$network/pieces/$cid': typeof NetworkPiecesCidRoute
  '/$network/providers/$id': typeof NetworkProvidersIdRoute
  '/$network/rails/$id': typeof NetworkRailsIdRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/dashboard/data-sets/$id': typeof DashboardDataSetsIdRoute
  '/$network/data-sets/': typeof NetworkDataSetsIndexRoute
  '/$network/providers/': typeof NetworkProvidersIndexRoute
  '/$network/rails/': typeof NetworkRailsIndexRoute
  '/$network/session-keys/': typeof NetworkSessionKeysIndexRoute
  '/dashboard/data-sets/': typeof DashboardDataSetsIndexRoute
  '/.well-known/agent-skills/fil/SKILL.md': typeof DotwellKnownAgentSkillsFilSKILLDotmdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$network'
    | '/dashboard'
    | '/docs'
    | '/agents'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$network/search'
    | '/.well-known/api-catalog'
    | '/.well-known/mcp-server-card'
    | '/dashboard/account'
    | '/dashboard/approvals'
    | '/dashboard/rails'
    | '/dashboard/session-keys'
    | '/dashboard/setup'
    | '/dashboard/upload'
    | '/docs/$slug'
    | '/$network/'
    | '/dashboard/'
    | '/docs/'
    | '/$network/address/$address'
    | '/$network/data-sets/$id'
    | '/$network/pieces/$cid'
    | '/$network/providers/$id'
    | '/$network/rails/$id'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/dashboard/data-sets/$id'
    | '/$network/data-sets/'
    | '/$network/providers/'
    | '/$network/rails/'
    | '/$network/session-keys/'
    | '/dashboard/data-sets/'
    | '/.well-known/agent-skills/fil/SKILL.md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$network/search'
    | '/.well-known/api-catalog'
    | '/.well-known/mcp-server-card'
    | '/dashboard/account'
    | '/dashboard/approvals'
    | '/dashboard/rails'
    | '/dashboard/session-keys'
    | '/dashboard/setup'
    | '/dashboard/upload'
    | '/docs/$slug'
    | '/$network'
    | '/dashboard'
    | '/docs'
    | '/$network/address/$address'
    | '/$network/data-sets/$id'
    | '/$network/pieces/$cid'
    | '/$network/providers/$id'
    | '/$network/rails/$id'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/dashboard/data-sets/$id'
    | '/$network/data-sets'
    | '/$network/providers'
    | '/$network/rails'
    | '/$network/session-keys'
    | '/dashboard/data-sets'
    | '/.well-known/agent-skills/fil/SKILL.md'
  id:
    | '__root__'
    | '/'
    | '/$network'
    | '/dashboard'
    | '/docs'
    | '/agents'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$network/search'
    | '/.well-known/api-catalog'
    | '/.well-known/mcp-server-card'
    | '/dashboard/account'
    | '/dashboard/approvals'
    | '/dashboard/rails'
    | '/dashboard/session-keys'
    | '/dashboard/setup'
    | '/dashboard/upload'
    | '/docs/$slug'
    | '/$network/'
    | '/dashboard/'
    | '/docs/'
    | '/$network/address/$address'
    | '/$network/data-sets/$id'
    | '/$network/pieces/$cid'
    | '/$network/providers/$id'
    | '/$network/rails/$id'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/dashboard/data-sets/$id'
    | '/$network/data-sets/'
    | '/$network/providers/'
    | '/$network/rails/'
    | '/$network/session-keys/'
    | '/dashboard/data-sets/'
    | '/.well-known/agent-skills/fil/SKILL.md'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetworkRouteRoute: typeof NetworkRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  DotwellKnownMcpServerCardRoute: typeof DotwellKnownMcpServerCardRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute
  DotwellKnownAgentSkillsFilSKILLDotmdRoute: typeof DotwellKnownAgentSkillsFilSKILLDotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$network': {
      id: '/$network'
      path: '/$network'
      fullPath: '/$network'
      preLoaderRoute: typeof NetworkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$network/': {
      id: '/$network/'
      path: '/'
      fullPath: '/$network/'
      preLoaderRoute: typeof NetworkIndexRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/search': {
      id: '/$network/search'
      path: '/search'
      fullPath: '/$network/search'
      preLoaderRoute: typeof NetworkSearchRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp-server-card': {
      id: '/.well-known/mcp-server-card'
      path: '/.well-known/mcp-server-card'
      fullPath: '/.well-known/mcp-server-card'
      preLoaderRoute: typeof DotwellKnownMcpServerCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rails': {
      id: '/dashboard/rails'
      path: '/rails'
      fullPath: '/dashboard/rails'
      preLoaderRoute: typeof DashboardRailsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/session-keys': {
      id: '/dashboard/session-keys'
      path: '/session-keys'
      fullPath: '/dashboard/session-keys'
      preLoaderRoute: typeof DashboardSessionKeysRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setup': {
      id: '/dashboard/setup'
      path: '/setup'
      fullPath: '/dashboard/setup'
      preLoaderRoute: typeof DashboardSetupRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/$network/address/$address': {
      id: '/$network/address/$address'
      path: '/address/$address'
      fullPath: '/$network/address/$address'
      preLoaderRoute: typeof NetworkAddressAddressRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/data-sets/': {
      id: '/$network/data-sets/'
      path: '/data-sets'
      fullPath: '/$network/data-sets/'
      preLoaderRoute: typeof NetworkDataSetsIndexRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/data-sets/$id': {
      id: '/$network/data-sets/$id'
      path: '/data-sets/$id'
      fullPath: '/$network/data-sets/$id'
      preLoaderRoute: typeof NetworkDataSetsIdRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/pieces/$cid': {
      id: '/$network/pieces/$cid'
      path: '/pieces/$cid'
      fullPath: '/$network/pieces/$cid'
      preLoaderRoute: typeof NetworkPiecesCidRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/providers/': {
      id: '/$network/providers/'
      path: '/providers'
      fullPath: '/$network/providers/'
      preLoaderRoute: typeof NetworkProvidersIndexRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/providers/$id': {
      id: '/$network/providers/$id'
      path: '/providers/$id'
      fullPath: '/$network/providers/$id'
      preLoaderRoute: typeof NetworkProvidersIdRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/rails/': {
      id: '/$network/rails/'
      path: '/rails'
      fullPath: '/$network/rails/'
      preLoaderRoute: typeof NetworkRailsIndexRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/rails/$id': {
      id: '/$network/rails/$id'
      path: '/rails/$id'
      fullPath: '/$network/rails/$id'
      preLoaderRoute: typeof NetworkRailsIdRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/$network/session-keys/': {
      id: '/$network/session-keys/'
      path: '/session-keys'
      fullPath: '/$network/session-keys/'
      preLoaderRoute: typeof NetworkSessionKeysIndexRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/data-sets/': {
      id: '/dashboard/data-sets/'
      path: '/data-sets'
      fullPath: '/dashboard/data-sets/'
      preLoaderRoute: typeof DashboardDataSetsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/data-sets/$id': {
      id: '/dashboard/data-sets/$id'
      path: '/data-sets/$id'
      fullPath: '/dashboard/data-sets/$id'
      preLoaderRoute: typeof DashboardDataSetsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/.well-known/agent-skills/fil/SKILL.md': {
      id: '/.well-known/agent-skills/fil/SKILL.md'
      path: '/.well-known/agent-skills/fil/SKILL.md'
      fullPath: '/.well-known/agent-skills/fil/SKILL.md'
      preLoaderRoute: typeof DotwellKnownAgentSkillsFilSKILLDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NetworkRouteRouteChildren {
  NetworkSearchRoute: typeof NetworkSearchRoute
  NetworkIndexRoute: typeof NetworkIndexRoute
  NetworkAddressAddressRoute: typeof NetworkAddressAddressRoute
  NetworkDataSetsIdRoute: typeof NetworkDataSetsIdRoute
  NetworkPiecesCidRoute: typeof NetworkPiecesCidRoute
  NetworkProvidersIdRoute: typeof NetworkProvidersIdRoute
  NetworkRailsIdRoute: typeof NetworkRailsIdRoute
  NetworkDataSetsIndexRoute: typeof NetworkDataSetsIndexRoute
  NetworkProvidersIndexRoute: typeof NetworkProvidersIndexRoute
  NetworkRailsIndexRoute: typeof NetworkRailsIndexRoute
  NetworkSessionKeysIndexRoute: typeof NetworkSessionKeysIndexRoute
}

const NetworkRouteRouteChildren: NetworkRouteRouteChildren = {
  NetworkSearchRoute: NetworkSearchRoute,
  NetworkIndexRoute: NetworkIndexRoute,
  NetworkAddressAddressRoute: NetworkAddressAddressRoute,
  NetworkDataSetsIdRoute: NetworkDataSetsIdRoute,
  NetworkPiecesCidRoute: NetworkPiecesCidRoute,
  NetworkProvidersIdRoute: NetworkProvidersIdRoute,
  NetworkRailsIdRoute: NetworkRailsIdRoute,
  NetworkDataSetsIndexRoute: NetworkDataSetsIndexRoute,
  NetworkProvidersIndexRoute: NetworkProvidersIndexRoute,
  NetworkRailsIndexRoute: NetworkRailsIndexRoute,
  NetworkSessionKeysIndexRoute: NetworkSessionKeysIndexRoute,
}

const NetworkRouteRouteWithChildren = NetworkRouteRoute._addFileChildren(
  NetworkRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardRailsRoute: typeof DashboardRailsRoute
  DashboardSessionKeysRoute: typeof DashboardSessionKeysRoute
  DashboardSetupRoute: typeof DashboardSetupRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDataSetsIdRoute: typeof DashboardDataSetsIdRoute
  DashboardDataSetsIndexRoute: typeof DashboardDataSetsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardRailsRoute: DashboardRailsRoute,
  DashboardSessionKeysRoute: DashboardSessionKeysRoute,
  DashboardSetupRoute: DashboardSetupRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDataSetsIdRoute: DashboardDataSetsIdRoute,
  DashboardDataSetsIndexRoute: DashboardDataSetsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetworkRouteRoute: NetworkRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  AgentsRoute: AgentsRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  DotwellKnownMcpServerCardRoute: DotwellKnownMcpServerCardRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  DotwellKnownAgentSkillsFilSKILLDotmdRoute:
    DotwellKnownAgentSkillsFilSKILLDotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
