/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{network}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indexer status
         * @description Chain id and latest, safe and finalized indexed blocks.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Network status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{network}/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List storage providers */
        get: {
            parameters: {
                query?: {
                    /** @description Page size (1-200) */
                    limit?: number;
                    /** @description Opaque cursor from a previous response `nextCursor` */
                    cursor?: string;
                    /** @description Approved for Warm Storage */
                    approved?: "true" | "false";
                    /** @description Active in the provider registry */
                    active?: "true" | "false";
                    /** @description Endorsed provider */
                    endorsed?: "true" | "false";
                };
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Providers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderPage"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{network}/providers/{providerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a storage provider */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                    providerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Provider */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{network}/data-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List data sets */
        get: {
            parameters: {
                query?: {
                    /** @description Page size (1-200) */
                    limit?: number;
                    /** @description Opaque cursor from a previous response `nextCursor` */
                    cursor?: string;
                    /** @description Client address that owns the data set */
                    owner?: string;
                    /** @description Storage provider id */
                    provider_id?: string;
                    /** @description Deleted data sets */
                    deleted?: "true" | "false";
                    /** @description Data sets with CDN enabled */
                    with_cdn?: "true" | "false";
                };
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Data sets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataSetPage"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{network}/data-sets/{dataSetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a data set */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                    dataSetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Data set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataSetResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{network}/data-sets/{dataSetId}/pieces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pieces in a data set */
        get: {
            parameters: {
                query?: {
                    /** @description Page size (1-200) */
                    limit?: number;
                    /** @description Opaque cursor from a previous response `nextCursor` */
                    cursor?: string;
                    /** @description Removed pieces */
                    removed?: "true" | "false";
                };
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                    dataSetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pieces */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PiecePage"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{network}/data-sets/{dataSetId}/pieces/{pieceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a piece */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                    dataSetId: string;
                    pieceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Piece */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PieceResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{network}/pieces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find pieces by owner, PieceCID or provider
         * @description Requires at least one of owner, cid or provider_id.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page size (1-200) */
                    limit?: number;
                    /** @description Opaque cursor from a previous response `nextCursor` */
                    cursor?: string;
                    /** @description Client address that owns the data set */
                    owner?: string;
                    /** @description PieceCID */
                    cid?: string;
                    /** @description Storage provider id */
                    provider_id?: string;
                    /** @description Removed pieces */
                    removed?: "true" | "false";
                };
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pieces with data set owner and provider */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PieceWithDataSetPage"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{network}/rails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payment rails */
        get: {
            parameters: {
                query?: {
                    /** @description Page size (1-200) */
                    limit?: number;
                    /** @description Opaque cursor from a previous response `nextCursor` */
                    cursor?: string;
                    /** @description Payer address */
                    payer?: string;
                    /** @description Payee address */
                    payee?: string;
                    /** @description Operator contract address */
                    operator?: string;
                    /** @description Payment token address */
                    token?: string;
                    /** @description Rail lifecycle state */
                    state?: "active" | "terminated" | "finalized";
                };
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rails */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RailPage"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{network}/rails/{railId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a payment rail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                    railId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RailResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{network}/rails/{railId}/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rail settlements */
        get: {
            parameters: {
                query?: {
                    /** @description Page size (1-200) */
                    limit?: number;
                    /** @description Opaque cursor from a previous response `nextCursor` */
                    cursor?: string;
                };
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                    railId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Settlements */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettlementPage"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{network}/session-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List session keys
         * @description Latest expiry per permission for each (identity, signer) pair.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page size (1-200) */
                    limit?: number;
                    /** @description Opaque cursor from a previous response `nextCursor` */
                    cursor?: string;
                    /** @description Identity that authorized the key */
                    identity?: string;
                    /** @description Session key signer address */
                    signer?: string;
                    /** @description Keys with any unexpired permission */
                    active?: "true" | "false";
                };
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session keys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionKeyPage"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{network}/session-keys/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List session key authorization events */
        get: {
            parameters: {
                query?: {
                    /** @description Page size (1-200) */
                    limit?: number;
                    /** @description Opaque cursor from a previous response `nextCursor` */
                    cursor?: string;
                    /** @description Identity that authorized the key */
                    identity?: string;
                    /** @description Session key signer address */
                    signer?: string;
                };
                header?: never;
                path: {
                    /** @description Filecoin network */
                    network: "calibration" | "mainnet";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session key events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionKeyEventPage"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Network not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StatusResponse: {
            data: components["schemas"]["Status"];
        };
        Status: {
            network: string;
            chainId: number;
            indexers: components["schemas"]["IndexerStatus"][];
        };
        IndexerStatus: {
            schema: string;
            chainName: string;
            chainId: number;
            latest: components["schemas"]["Checkpoint"];
            safe: components["schemas"]["Checkpoint"];
            finalized: components["schemas"]["Checkpoint"];
        };
        Checkpoint: {
            blockNumber: number;
            timestamp: number;
        } | null;
        Error: {
            error: {
                /** @example not_found */
                code: string;
                message: string;
                issues?: unknown[];
            };
        };
        ProviderPage: {
            data: components["schemas"]["Provider"][];
            /** @description Cursor for the next page, or null on the last page */
            nextCursor: string | null;
        };
        Provider: {
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            providerId: string;
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            address: string;
            name: string | null;
            serviceUrl: string | null;
            active: boolean | null;
            pdpProductActive: boolean | null;
            approved: boolean | null;
            endorsed: boolean | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            createdAtBlock: string | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            updatedAtBlock: string | null;
        };
        ProviderResponse: {
            data: components["schemas"]["Provider"];
        };
        DataSetPage: {
            data: components["schemas"]["DataSet"][];
            /** @description Cursor for the next page, or null on the last page */
            nextCursor: string | null;
        };
        DataSet: {
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            dataSetId: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            providerId: string | null;
            /**
             * @description Client address that pays for the data set
             * @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd
             */
            owner: string | null;
            source: string | null;
            /**
             * @example {
             *       "source": "filecoin-pin"
             *     }
             */
            metadata: {
                [key: string]: unknown;
            } | null;
            withCdn: boolean | null;
            withIpfsIndexing: boolean | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            pdpEndEpoch: string | null;
            deleted: boolean | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            createdAtBlock: string | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            updatedAtBlock: string | null;
        };
        DataSetResponse: {
            data: components["schemas"]["DataSet"];
        };
        PiecePage: {
            data: components["schemas"]["Piece"][];
            /** @description Cursor for the next page, or null on the last page */
            nextCursor: string | null;
        };
        Piece: {
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            dataSetId: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            pieceId: string;
            /** @description PieceCID (v2) */
            cid: string | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            rawSize: string | null;
            /**
             * @example {
             *       "source": "filecoin-pin"
             *     }
             */
            metadata: {
                [key: string]: unknown;
            } | null;
            removed: boolean | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            addedAtBlock: string | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            removedAtBlock: string | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            updatedAtBlock: string | null;
        };
        PieceResponse: {
            data: components["schemas"]["Piece"];
        };
        PieceWithDataSetPage: {
            data: components["schemas"]["PieceWithDataSet"][];
            /** @description Cursor for the next page, or null on the last page */
            nextCursor: string | null;
        };
        PieceWithDataSet: components["schemas"]["Piece"] & {
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            owner: string | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            providerId: string | null;
        };
        RailPage: {
            data: components["schemas"]["Rail"][];
            /** @description Cursor for the next page, or null on the last page */
            nextCursor: string | null;
        };
        Rail: {
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            railId: string;
            /**
             * @description Rail lifecycle state
             * @enum {string}
             */
            state: "active" | "terminated" | "finalized";
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            payer: string;
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            payee: string;
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            token: string;
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            operator: string;
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            validator: string;
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            serviceFeeRecipient: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            commissionRateBps: string;
            /**
             * @description Current payment rate in token base units per epoch
             * @example 1
             */
            paymentRate: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            lockupPeriod: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            lockupFixed: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            endEpoch: string | null;
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            terminatedBy: string | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            settledUpTo: string | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            totalSettledAmount: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            totalNetPayeeAmount: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            createdAtBlock: string;
            /** @description Unix timestamp */
            createdAt: number;
            txHash: string;
        };
        RailResponse: {
            data: components["schemas"]["Rail"];
        };
        SettlementPage: {
            data: components["schemas"]["Settlement"][];
            /** @description Cursor for the next page, or null on the last page */
            nextCursor: string | null;
        };
        Settlement: {
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            railId: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            totalSettledAmount: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            totalNetPayeeAmount: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            operatorCommission: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            networkFee: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            settledUpTo: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            blockNumber: string;
            timestamp: number;
            txHash: string;
        };
        SessionKeyPage: {
            data: components["schemas"]["SessionKey"][];
            /** @description Cursor for the next page, or null on the last page */
            nextCursor: string | null;
        };
        SessionKey: {
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            identity: string;
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            signer: string;
            /** @description Whether any permission is unexpired */
            active: boolean;
            /**
             * @description Latest permission expiry
             * @example 1
             */
            expiry: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            updatedAtBlock: string;
            permissions: components["schemas"]["SessionKeyPermission"][];
        };
        SessionKeyPermission: {
            /** @description EIP-712 typehash the signer may sign for */
            permission: string;
            /**
             * @description Known Warm Storage operation for the typehash
             * @example CreateDataSet
             */
            name: string | null;
            /**
             * @description Unix timestamp; 0 when revoked
             * @example 1
             */
            expiry: string;
            active: boolean;
            origin: string | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            blockNumber: string;
            txHash: string;
        };
        SessionKeyEventPage: {
            data: components["schemas"]["SessionKeyEvent"][];
            /** @description Cursor for the next page, or null on the last page */
            nextCursor: string | null;
        };
        SessionKeyEvent: {
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            identity: string;
            /** @example 0x480c51fe9fc90e01fa742c51300cc29e151a71cd */
            signer: string;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            expiry: string;
            permissions: string[];
            origin: string | null;
            /**
             * @description Unsigned integer as a decimal string
             * @example 1
             */
            blockNumber: string;
            timestamp: number;
            txHash: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
